trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  imageName: 'PartsE2E'
  tag: '$(Build.BuildId)'  # Tag the Docker image with the build ID

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Docker Build and Push Steps
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    repository: '$(imageName)'  # The image name variable is used here
    command: 'build'
    Dockerfile: '**/Dockerfile'  # Path to Dockerfile (ensure this is correct)
    tags: |
      $(tag)

- task: Docker@2
  displayName: 'Push Docker Image to Registry'
  inputs:
    repository: '$(imageName)'  # The image name variable is used here
    command: 'push'
    tags: |
      $(tag)
